import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from './providers';
import { Theme } from '@radix-ui/themes';
import './globals.css';
import '@radix-ui/themes/styles.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Providers>
					<main className="dark text-foreground bg-background">
					<Theme>{children}</Theme>
					</main>
				
				</Providers>
			</body>
		</html>
	);
}
